apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: postgres-password
spec:
  secretTemplate:
    type: Opaque
    #The secretgen-controller will create a secret with this content.
    stringData:
      password: $(value)
