apiVersion: v1
kind: Service
metadata:
  name: {{ include "titanic.fullname" . }}
  labels:
    app: titanic
spec:
  type: {{ .Values.service.type }}
  #HTTPS would be implemented by an ingress where TLS termination would happen. Istio adds mTLS for cluster-internal traffic.
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: titanic
