version: '3.7'

services:
  titanic:
    image: titanic
    ports:
    - "8080:8080"
    environment:
    - DB_HOST=postgres
    - DB_PORT=5432
    - DB_USER=titanic
    - DB_PASSWORD=titanic
    - DB_NAME=titanic
  postgres:
    image: postgres:15.1-alpine
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=titanic
    - POSTGRES_PASSWORD=titanic
    - POSTGRES_DB=titanic
    volumes:
    - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local
